@echo off
echo Starting Groq API Proxy Server...
start cmd /k "node groq-proxy.js"
echo Wait for server to start...
timeout /t 2 /nobreak
echo Opening chatbot in browser...
start "" "chatbot.html"
echo If the chatbot doesn't open automatically, please open chatbot.html directly in your browser
